//
// Created by jadjer on 02.02.25.
//

#pragma once

enum EventType {
  EVENT_TWIST_POSITION_UPDATE,
  EVENT_TWIST_POSITION_ERROR,

  EVENT_THROTTLE_UPDATE,
  EVENT_THROTTLE_ERROR,

  EVENT_MODE_BUTTON_PRESS,
  EVENT_MODE_BUTTON_HOLD,

  EVENT_BREAK_SWITCH_ENABLE,
  EVENT_CLUTCH_SWITCH_ENABLE,
  EVENT_GUARD_SWITCH_ENABLE,

  EVENT_CRUISE_READY,
  EVENT_CRUISE_ENABLE,
  EVENT_CRUISE_DISABLE,
};
